### ISSUE TITLE
Scrollbar not moving on mobile

### ISSUE THREAD

**Issue by Donkfather** [luiguild/v-bar#4]
Hi, in the demo the scrollbar is not moving. Samsung S4 with Chrome

**Comment by appinteractive** [comment]
Same on iPhone with safari. Seams you are using the wrong events here.

**Comment by breadlesscode** [comment]
Same Android 6 - Chrome. Elephone C1.

**Comment by luiguild** [comment]
You can understand more about it on #2

**Comment by romandragan** [comment]
@luiguild, @Donkfather, @appinteractive, @breadlesscode, as a workaround we can just hide `v-bar` when screen is touch:

```css
@media (pointer: coarse) {
    .bar--vertical, .bar--horizontal
        display: none;
}
```
